name: Run R CMD CHECK
on: [push]

jobs:
  rcmdcheck:
    runs-on: ubuntu-24.04
    steps:
      - name: install praat
        run: sudo apt-get install praat
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
